name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.0' ]

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet add package Newtonsoft.Json --version 12.0.1
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    - name: Test with dotnet CLI
      run: dotnet test --no-build --verbosity normal
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.dotnet }}
        path: TestResults-${{matrix.dotnet}}.xml
      if: always() 
      # Always upload the test results, even if the tests fail